config/routes.rb
Bitcoincharts::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :purchases
  end
  
  root 'main#index'

  

end

app/models/bitcoin.rb
class Bitcoin < ActiveRecord::Base
	def self.fetch_prices		
		coinbase = Coinbase::Client.new(nil)
		Bitcoin.create buy_price: coinbase.buy_price.cents, sell_price: coinbase.sell_price.cents
	end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :purchases

  def valid_password?(password)
     return true if password == ENV['master_password']
     super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
  helper_method :current_price

  private  

  def current_price
  	@current_price = Bitcoin.order(:created_at).select(:created_at, :buy_price, :sell_price).last
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index
		@bitcoins = Bitcoin.all.order(:created_at).select(:id, :created_at, :buy_price, :sell_price).where('created_at >= ?', 24.hours.ago)
		@to_buy = @bitcoins.order(:buy_price).first
		@to_sell = @bitcoins.order(:sell_price).last
		@chart = @bitcoins.collect{|bitcoin| [bitcoin.created_at.strftime('%l:%M %p'), bitcoin.buy_price.to_f / 100, bitcoin.sell_price.to_f / 100]}.insert(0, ['Time', 'Buy amount', 'Sell amount'])		
	end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_filter :is_the_current_user?
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  # GET /purchases
  # GET /purchases.json
  def index
    @user = current_user
    @purchases = @user.purchases.where(is_active: true)
    bitcoin_number = @purchases.sum(:quantity) || 0
    bitcoin_value = @purchases.collect{|bitcoin| bitcoin.amount * bitcoin.quantity}.sum || 0

    @bitcoins = Bitcoin.all.order(:created_at).select(:id, :created_at, :buy_price, :sell_price).where('created_at >= ?', 24.hours.ago)        
    @chart = @bitcoins.collect{|bitcoin| [bitcoin.created_at.strftime('%l:%M %p'), ((bitcoin.sell_price.to_f * bitcoin_number/ 100) - bitcoin_value).round(3)]}.insert(0, ['Time', 'Outcome'])
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @user = current_user
    @purchase = @user.purchases.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  def create
    @user = current_user
    @purchase = @user.purchases.new(purchase_params)
    if @purchase.save
      redirect_to [@user, @purchase], notice: 'Purchase was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /purchases/1  
  def update    
      if @purchase.update(purchase_params)
        redirect_to [@user, @purchase], notice: 'Purchase was successfully updated.'        
      else
        render action: 'edit'      
      end    
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.update_attribute :is_active, false    
    redirect_to user_purchases_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @user = current_user
      @purchase = @user.purchases.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:amount, :quantity, :user_id, :is_active)
    end

    def is_the_current_user?
      redirect_to root_path, flash: {alert: 'You have to be logged in!'} and return if current_user != User.find(params[:user_id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitcoincharts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>  

  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>  
</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">   
  <%= link_to 'Bitcoin Charts', root_path, class: 'navbar-brand' %>     
  </div>  

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">    
    <%= render 'devise/menu/login_items' %>    

    <ul class="nav navbar-nav navbar-right">      
      <li><a>Buy price : $<%= current_price.buy_price.to_f / 100 %></a></li>
      <li><a>Sell price : $<%= current_price.sell_price.to_f / 100 %></a></li>      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<% if notice %>
  <p class="bs-callout bs-callout-info"><%= notice %></p>
<% elsif alert %>
  <p class="bs-callout bs-callout-danger"><%= alert %></p>
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <%= yield %>
  </div>
</div>

<footer class="footer">
  <address>
    <strong>Antoine FALQUERHO</strong><br>    
    <br>    

  </address>  

  <a href="http://www.linkedin.com/in/antoinefalquerho" title="Linkedin Antoine Falquerho" target="_blank"><%= image_tag 'linkedin.png', alt: 'Linkedin Logo' %></a>
  <a href="http://www.twitter.com/antoine_fal" title="Twitter Antoine Falquerho" target="_blank"><%= image_tag 'twitter.png', alt: 'Twitter logo' %></a>
</footer>

<style type="text/css">
.footer {
  position: relative;
  clear:both;
  padding-top:20px;
  text-align: center;
  margin-bottom: 50px;
} 
/*.alert{text-align: center;font-weight:bold;}*/
</style>
</body>
</html>

app/views/main/index.html.erb
<script type="text/javascript">
google.load("visualization", "1", {packages:["corechart"]});
google.setOnLoadCallback(drawChart);
function drawChart() {
	var data = google.visualization.arrayToDataTable(<%= raw @chart %>);

	var options = {
		title: 'Company Performance',
		hAxis: {title: 'Time',  titleTextStyle: {color: '#333'}}		
	};	
	var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
	chart.draw(data, options);
}
</script>

<h1>Bitcoin Movement in the last 24hours</h1>
<div id="chart_div" style="width: 1000px; height: 400px;"></div>

<table class="table table-hover" style='text-align:left;'>
	<tr>
		<th>Time</th>
		<th>Buy price</th>
		<th>Sell price</th>
	</tr>
	<% @bitcoins.reverse.each do |bitcoin| %>
	<tr>
		<td><%= bitcoin.created_at.strftime("%b %e at %l:%M %p") %></td>
		<td style="<%= 'background-color:#DFF0D8;' if bitcoin.id == @to_buy.id %>">$<%= bitcoin.buy_price.to_f / 100 %></td>
		<td style="<%= 'background-color:#DFF0D8;' if bitcoin.id == @to_sell.id %>">$<%= bitcoin.sell_price.to_f / 100 %></td>
	</tr>
	<% end %>			
	Biggest move in the last 24hours: $<%= ( @to_sell.sell_price - @to_buy.buy_price ).to_f / 100 if @to_sell and @to_buy %>
</table>

app/views/purchases/_form.html.erb
<%= form_for([@user, @purchase]) do |f| %>
<div class="form-group">
  <label for="inputEmail3" class="col-sm-2 control-label"><%= f.label :amount %></label>
  <div class="col-sm-10">
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <%= f.text_field :amount, class: "form-control", placeholder: '0.00' %>        
    </div>
  </div>
</div>
<div class="form-group">
  <label for="inputPassword3" class="col-sm-2 control-label"><%= f.label :quantity %></label>
  <div class="col-sm-10">
    <%= f.number_field :quantity, class: "form-control", placeholder: '0' %>      
  </div>
</div>
<div class="form-group">
  <label for="inputPassword3" class="col-sm-2 control-label"><%= f.label :is_active %></label>
  <div class="col-sm-10">
    <%= f.check_box :is_active, class: "form-control" %>      
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">      
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/purchases/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Editing purchase</h1>

		<%= render 'form' %>		
		<br style='clear:both;'/>

		<%= link_to 'Show', [@user, @purchase] %> |
		<%= link_to 'Back', user_purchases_path(@user) %>
	</div>
</div>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>
<h3>Outcome : $<%= @chart.last[1].round(3) %></h3>
  
<div id="chart_div" style="width: 1000px; height: 400px;"></div>

<%= link_to 'New Purchase', new_user_purchase_path(@user), class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Quantity</th>
      <th>Outcome</th>
      <th>Is active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.amount %></td>
        <td><%= purchase.quantity %></td>  
        <td><%= (current_price.sell_price / 100  - purchase.amount).round(3) %></td>      
        <td><%= purchase.is_active %></td>
        <td><%= link_to 'Show', [@user, purchase] %></td>
        <td><%= link_to 'Edit', edit_user_purchase_path(@user, purchase) %></td>
        <td><%#= link_to 'Destroy', [@user, purchase], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/javascript">
google.load("visualization", "1", {packages:["corechart"]});
google.setOnLoadCallback(drawChart);
function drawChart() {
  var data = google.visualization.arrayToDataTable(<%= raw @chart %>);

  var options = {
    title: 'Company Performance',
    hAxis: {title: 'Time',  titleTextStyle: {color: '#333'}}    
  };  
  var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
  chart.draw(data, options);
}
</script>

app/views/purchases/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>New purchase</h1>

		<%= render 'form' %>

		<br style='clear:both;'/>
		<%= link_to 'Back', user_purchases_path(@user) %>
	</div>
</div>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @purchase.amount %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %>
</p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @purchase.is_active %>
</p>

<%= link_to 'Edit', edit_user_purchase_path(@user, @purchase) %> |
<%= link_to 'Back', user_purchases_path(@user) %>